server {
    listen 80;
    server_name linggui.hk.qmxz.dpdns.org;
    root /www/sites/linggui.hk.qmxz.dpdns.org/index;
    index index.html;

    access_log /www/sites/linggui.hk.qmxz.dpdns.org/log/access.log main;
    error_log /www/sites/linggui.hk.qmxz.dpdns.org/log/error.log;

    location ^~ /.well-known/acme-challenge/ {
        root /usr/share/nginx/html;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
